version: "2"
services:
  elasticsearch:
    #privileged: true
    image: elasticsearch:7.9.1
    environment:
      - http.host=0.0.0.0
      - discovery.type=single-node
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - es-data:/usr/share/elasticsearch/data
      #- ./vol/elasticsearch/logs:/usr/share/elasticsearch/logs

  cortex:
    image: thehiveproject/cortex:3.1.0-1
    depends_on:
      - elasticsearch
    ports:
      - "0.0.0.0:9001:9001"
    command:
        --analyzer-url "https://download.thehive-project.org/analyzers.json"

  thehive:
    image: thehiveproject/thehive:3.5.0-1
    depends_on:
      - elasticsearch
      - cortex
    ports:
      - "0.0.0.0:9000:9000"
    command: '--cortex-port 9001 --cortex-key ${CORTEX_KEY}'

volumes:
  es-data:
