version: "2"
services:
  elasticsearch:
    #privileged: true
    image: elasticsearch:7.9.1
    environment:
      - http.host=0.0.0.0
      - discovery.type=single-node
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - es-data:/usr/share/elasticsearch/data

  cortex:
    image: thehiveproject/cortex:3.1.0-1
    depends_on:
      - elasticsearch
    ports:
      - "0.0.0.0:9001:9001"
    command: '--start-docker'
    volumes:
      - './vol/cortex/application.conf:/etc/cortex/application.conf'
      # IMPORTANT
      # The Cortex Container uses this Docker Hosts "Docker Process" for running its own Analyzer Containers (called "Neurons") on analysis demand.
      # -> Configure these settings to match your Docker Host paths (left side of the ":") to the right paths!      
      - /var/run/docker.sock:/var/run/docker.sock
      # -> This folder must exist on the Docker host and the correct Docker Host path (left side of the ":") needs to be specified!
      - /tmp/cortex-jobs:/tmp/cortex-jobs
    environment:
      # IMPORTANT
      # The Cortex Container uses this Docker Host for running its own Analyzer Containers (called "Neurons") on analysis demand.
      # -> These two folders must exist on the Docker host!
      # -> The Container needs access to these two folders!
      - job_directory=/tmp/cortex-jobs
      - docker-job-directory=/var/run/cortex/jobs

  thehive:
    image: thehiveproject/thehive:3.5.0-1
    depends_on:
      - elasticsearch
      - cortex
    ports:
      - "0.0.0.0:9000:9000"
    command: '--cortex-port 9001 --cortex-key ${CORTEX_KEY}'

volumes:
  es-data:
